### PR TITLE
NetInfo will Deprecated and replace with react-native-community/netinfo

### PR DESCRIPTION
**Pull request by laksithakumara**

### CODE REVIEW

**Comment by mifi** [comment]
Maybe the developer should send NetInfo into NetworkProvider instead, so we don't need to have a dependency on a specific version. If we are going to have a dependency on react-native-community/netinfo, then we also need to include native linking instructions from there.

**Comment by flexbox** [comment]
Hey @laksithakumara Thank for the PR
But there is another one who's already merged 
https://github.com/rgommezz/react-native-offline/pull/178

Can you close this issue if it solves your problem? 🙏

**Comment by tconn89** [comment]
[#178](https://github.com/rgommezz/react-native-offline/pull/178) will not be completed.  Can we resume this PR?

Again, we cannot migrate to React Native 0.60 until NetInfo dependency is resolved.

**Comment by rgommezz** [comment]
I'll take care of it in the next days:

https://github.com/rgommezz/react-native-offline/issues/172#issuecomment-508163397

**Pull request closed without merging**
