### PR TITLE
Check connectivity interval offline only

### PR DESCRIPTION
**Pull request by DCKT**
Hello,

I've a case where I want to put a small interval but only when the app is disconnected (it would be overkill for the app connected).

By the way, I've updated to the latest prettier package, I had some bug with the previous version.

### CODE REVIEW

**Comment by rauliyohmc** [comment]
Hi @DCKT, I don't understand why the whole Readme had to be reformated, since you just had to add one or two lines, concretely:

> `checkIntervalOfflineOnly`: boolean who trigger the interval function only if there is no connection when set to `true`. Defaults to `false`.

Do you have some plugin on your editor that has different config for markdown files?

Could you please revert the rest?

**Comment by DCKT** [comment]
My bad @rauliyohmc it's my prettier config. I will revert this one

**Comment by thymikee** [comment]
Would be great to land this feature, as this PR looks good to go. 
@rgommezz you should be good to resolve the conflicts using GitHub UI.

**Comment by thymikee** [comment]
Ping

**Comment by thymikee** [comment]
Awesome, thanks @rgommezz ❤️. Lemme know when it's out :)

**Comment by rgommezz** [comment]
Version 3.13.0 out @thymikee  🎉

**Pull request merged**
